---
abstract: 'A selection of utilities for data and data types'
author:
  - 'Goro Fuji(gfx) <gfuji(at)cpan.org>.'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Hash::Util::FieldHash::Compat: 0
  Scope::Guard: 0
  Test::Exception: 0.27
  Test::More: 0.62
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Util
name: Data-Util
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-Data-Util.git
version: 0.59
