--- #YAML:1.0
name:               Data-Util
version:            0.02
abstract:           various utility functions
author:
    - Lukas Mai <l.mai@web.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Defaults::Mauke:  0
    Exporter:         5.57
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
